from __future__ import annotations

import logging
import os
import tempfile
import time
from dataclasses import dataclass
from http.cookiejar import MozillaCookieJar
from pathlib import Path
from typing import Any

from .browser_session import BrowserUnavailableError, persistent_context
from .config import Settings

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class RefreshProfile:
    """How to refresh one platform's cookies from a persistent browser profile."""

    site_url: str
    cookie_domain: str
    required_names: frozenset[str]


# Platforms whose exported cookies expire and can be refreshed from a logged-in
# persistent Chromium profile. SESSDATA / auth_token are the session anchors used
# both to detect "logged in" and to judge staleness.
_PROFILES: dict[str, RefreshProfile] = {
    "bilibili": RefreshProfile(
        site_url="https://www.bilibili.com/",
        cookie_domain="bilibili.com",
        required_names=frozenset({"SESSDATA"}),
    ),
    "x": RefreshProfile(
        site_url="https://x.com/home",
        cookie_domain="x.com",
        required_names=frozenset({"auth_token", "ct0"}),
    ),
}

# Per-process throttle so a burst of stale-cookie requests does not launch the
# browser repeatedly. Keyed by platform, monotonic timestamps.
_last_refresh: dict[str, float] = {}


def _domain_matches(cookie_domain: str, want: str) -> bool:
    d = cookie_domain.lstrip(".")
    return d == want or d.endswith(f".{want}")


def _resolve_target(platform: str, settings: Settings) -> str | None:
    """Resolve the per-platform cookie file to refresh into.

    Never returns the shared unified cookie_file: writing refreshed cookies there
    would clobber other platforms. If only the shared file is configured, refresh
    is skipped with a warning pointing at platform_cookie_files.
    """
    configured = settings.platform_cookie_files.get(platform, "")
    if configured:
        return configured
    if settings.cookie_file and Path(settings.cookie_file).exists():
        logger.warning(
            "cookie_refresh for %s needs a platform_cookie_files entry; the shared "
            "cookie_file would otherwise shadow the refreshed per-platform file",
            platform,
        )
        return None
    for cookie_dir in (Path("/etc/feishu-link/cookies"), Path("cookies")):
        candidate = cookie_dir / f"{platform}.txt"
        if candidate.exists():
            return str(candidate)
    return str(Path("cookies") / f"{platform}.txt")


def cookie_is_stale(cookie_file: str, platform: str, stale_before_seconds: int) -> bool:
    """True if the platform's required cookies are missing or near expiry."""
    profile = _PROFILES.get(platform)
    if profile is None:
        return False

    path = Path(cookie_file)
    if not path.exists():
        return True

    jar = MozillaCookieJar(str(path))
    try:
        jar.load(ignore_discard=True, ignore_expires=True)
    except Exception as exc:
        logger.warning("Cannot parse %s for staleness: %s", cookie_file, exc)
        return True

    expiries: dict[str, int | None] = {}
    for cookie in jar:
        if cookie.name in profile.required_names and _domain_matches(
            cookie.domain, profile.cookie_domain
        ):
            expiries[cookie.name] = cookie.expires

    if not profile.required_names <= set(expiries):
        return True

    threshold = time.time() + stale_before_seconds
    return any(exp is not None and exp <= threshold for exp in expiries.values())


def _write_netscape(cookies: list[dict[str, Any]], path: str) -> None:
    """Atomically write Playwright cookies as a Netscape cookie file."""
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Netscape HTTP Cookie File",
        "# Auto-generated by feishu-link cookie refresh; do not edit.",
        "",
    ]
    for cookie in cookies:
        domain = str(cookie.get("domain", ""))
        name = str(cookie.get("name", ""))
        if not domain or not name:
            continue
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        cpath = str(cookie.get("path") or "/")
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        expires = cookie.get("expires")
        expiry = int(expires) if isinstance(expires, int | float) and expires > 0 else 0
        prefix = "#HttpOnly_" if cookie.get("httpOnly") else ""
        value = str(cookie.get("value", ""))
        lines.append(
            f"{prefix}{domain}\t{include_sub}\t{cpath}\t{secure}\t{expiry}\t{name}\t{value}"
        )

    content = "\n".join(lines) + "\n"
    fd, tmp = tempfile.mkstemp(dir=str(target.parent), prefix=".cookies-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
        os.replace(tmp, target)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise


async def refresh_cookies(
    platform: str,
    settings: Settings,
    *,
    target: str | None = None,
) -> bool:
    """Export fresh cookies from the platform's persistent profile to its file."""
    profile = _PROFILES.get(platform)
    if profile is None:
        logger.warning("No cookie-refresh profile for platform %s", platform)
        return False

    if target is None:
        target = _resolve_target(platform, settings)
    if not target:
        return False

    profile_dir = str(Path(settings.cookie_refresh_profile_dir) / platform)
    timeout_ms = int(settings.cookie_refresh_browser_timeout * 1000)
    try:
        async with persistent_context(
            profile_dir,
            headless=settings.cookie_refresh_browser_headless,
            timeout_ms=timeout_ms,
        ) as context:
            page = context.pages[0] if context.pages else await context.new_page()
            await page.goto(profile.site_url, wait_until="domcontentloaded", timeout=timeout_ms)
            raw = await context.cookies()
    except BrowserUnavailableError as exc:
        logger.warning("Cookie refresh for %s unavailable: %s", platform, exc)
        return False
    except Exception as exc:
        logger.warning("Cookie refresh for %s failed: %s", platform, exc)
        return False

    cookies = [
        c for c in raw if _domain_matches(str(c.get("domain", "")), profile.cookie_domain)
    ]
    if not profile.required_names <= {str(c.get("name", "")) for c in cookies}:
        logger.warning(
            "Cookie refresh for %s produced no logged-in session; run "
            "`python main.py --browser-login %s`",
            platform,
            platform,
        )
        return False

    _write_netscape(cookies, target)
    logger.info("Refreshed %d cookies for %s -> %s", len(cookies), platform, target)
    return True


async def ensure_fresh_cookies(platform: str, settings: Settings) -> None:
    """Refresh the platform's cookies before use if enabled, stale, and not throttled.

    No-op unless cookie_refresh is enabled for the platform. Refresh failures are
    logged and swallowed so the caller proceeds with whatever cookies exist.
    """
    if not settings.cookie_refresh_enabled:
        return
    if platform not in settings.cookie_refresh_platforms or platform not in _PROFILES:
        return

    target = _resolve_target(platform, settings)
    if not target:
        return
    if not cookie_is_stale(target, platform, settings.cookie_refresh_stale_before_seconds):
        return

    now = time.monotonic()
    last = _last_refresh.get(platform)
    if last is not None and now - last < settings.cookie_refresh_min_interval_seconds:
        return
    _last_refresh[platform] = now

    await refresh_cookies(platform, settings, target=target)
